// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fktsblchzslffbykmvcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdHNibGNoenNsZmZieWttdmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTMwMzEsImV4cCI6MjA2MTM4OTAzMX0.FyyQxMqlbp-WSCg486BgV4tkXZ_XbolMAKsmIQekeXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);